In [8]:
import pandas as pd
import numpy as np
df = pd.read_csv("cars.csv")

#### Check Duplicate Records

In [3]:
df[df.duplicated()]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

#### Drop Duplicate Records

In [10]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

#### Check missing or null values

In [11]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### Drop missing or null values

In [13]:
df.dropna(inplace=True)
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

#### Show top 10 average MSRP (Price) per car brand (rounded figure)?

In [23]:
df.groupby('Make')['MSRP'].mean().head(10).round().reset_index()

           Make       MSRP
0         Acura    35087.0
1    Alfa Romeo    61600.0
2  Aston Martin   198123.0
3          Audi    54574.0
4           BMW    62163.0
5       Bentley   247169.0
6       Bugatti  1757224.0
7         Buick    33770.0
8      Cadillac    56368.0
9     Chevrolet    35971.0

#### Show the average MSRP (price) per years (rounded figure)?

In [24]:
df.groupby('Year')['MSRP'].mean().round().reset_index()

    Year     MSRP
0   1990   2073.0
1   1991   2223.0
2   1992   2192.0
3   1993   2401.0
4   1994   2726.0
5   1995   3270.0
6   1996   3140.0
7   1997   4524.0
8   1998   4434.0
9   1999   3612.0
10  2000   3913.0
11  2001  73833.0
12  2002  55704.0
13  2003  68312.0
14  2004  55908.0
15  2005  53724.0
16  2006  39001.0
17  2007  41173.0
18  2008  80462.0
19  2009  59193.0
20  2010  60152.0
21  2011  65663.0
22  2012  71837.0
23  2013  55201.0
24  2014  71196.0
25  2015  52613.0
26  2016  52580.0
27  2017  45333.0

#### Show average Engine HP (power) rounded figure and MPG (efficiency) rounded figure per year?

Hint: Average of (city mpg + highway MPG)

In [22]:
df['MPG'] = (df['city mpg'] + df['highway MPG']) / 2

df.groupby('Year')[['Engine HP', 'MPG']].mean().round()

      Engine HP   MPG
Year
1990      154.0  21.0
1991      163.0  21.0
1992      155.0  22.0
1993      174.0  21.0
1994      167.0  21.0
1995      203.0  20.0
1996      201.0  21.0
1997      200.0  21.0
1998      224.0  20.0
1999      199.0  21.0
2000      202.0  21.0
2001      243.0  20.0
2002      244.0  19.0
2003      258.0  19.0
2004      260.0  19.0
2005      255.0  20.0
2006      248.0  20.0
2007      274.0  18.0
2008      298.0  19.0
2009      268.0  20.0
2010      269.0  20.0
2011      280.0  22.0
2012      293.0  22.0
2013      290.0  23.0
2014      311.0  23.0
2015      288.0  24.0
2016      290.0  24.0
2017      285.0  25.0

#### What percentage of cars are Compact, Midsize, or Large?

In [26]:
df['Vehicle Size'].value_counts(normalize=True).mul(100).round(2).loc[['Compact', 'Midsize', 'Large']].reset_index()

  Vehicle Size  proportion
0      Compact       36.81
1      Midsize       39.34
2        Large       23.85

#### Which vehicle styles are the most sold (most common) in the dataset?

In [29]:
df['Vehicle Style'].value_counts().reset_index()

          Vehicle Style  count
0               4dr SUV   2053
1                 Sedan   1801
2                 Coupe    922
3           Convertible    645
4         4dr Hatchback    639
5         2dr Hatchback    409
6                 Wagon    349
7       Crew Cab Pickup    334
8   Extended Cab Pickup    187
9    Regular Cab Pickup    176
10        Passenger Van    100
11    Passenger Minivan     61
12            Cargo Van     34
13              2dr SUV     14
14      Convertible SUV      6
15        Cargo Minivan      5

#### Which car brands have the most vehicles priced at $40,000 or more and with a popularity score of at least 1000?

In [31]:
df[(df['MSRP'] >= 40000) & (df['Popularity'] >= 1000)]['Make'].value_counts().reset_index()

           Make  count
0      Cadillac    354
1           BMW    269
2          Audi    224
3     Chevrolet    171
4       Porsche    123
5          Ford    105
6        Nissan     69
7       Ferrari     68
8   Lamborghini     52
9        Toyota     50
10        Dodge     49
11          Kia     16
12      Hyundai     13
13     Chrysler     12
14        Honda      8